### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by Rombusevil** [pp19dd/picker#1]
Hello Dino, I wrote a small utility to make my git workflow faster using this library you wrote.
I want to share my code under GPLv3 or another open source licence. 
Would you consider adding a licence to this project?

Thanks in advance

**Comment by pp19dd** [comment]
Gotcha, think I understand why you want this.  Would CC0 work for you?

**Comment by Rombusevil** [comment]
Yes, that'll be cool!

**Comment by pp19dd** [comment]
Alright, I've added a license file, and updated readme/picker code to state it's available under CC0.  Cheers!

**Comment by Rombusevil** [comment]
Thanks man! I'll upload my code in a couple of hours. Cheers!
