### ISSUE TITLE
In pypi, pleaaase

### ISSUE THREAD

**Issue by vindarel** [pp19dd/picker#2]
Hi !
You're the only library that allows multi-select (given [a SO answer](https://stackoverflow.com/questions/28425204/python-how-to-use-list-as-source-of-selection-for-user-input/33629179#33629179)), but I can't use it since it's not in pypi ! Are you willing to do it ?

thanks !

ps: btw, there's already a "picker" lib in pypi (https://pypi.python.org/pypi/picker)

**Comment by pp19dd** [comment]
Hmm, I'm a bit concerned about picking an appropriate name for the package in pypi, since it's so generic. Would pp19dd-picker be adequate?

**Comment by vindarel** [comment]
lol, it could if you can explain the "pp19dd" acronym :p 

pypick[er] would do, `pickcurses` is hilarious, `multicurseschoicepicker` is explicit, …

**Comment by pp19dd** [comment]
Well, pp19dd was a misheard lyric from the late 90's from [Dr. Octagon](https://www.youtube.com/watch?v=wB6hDkcWoBo).  At the time all I had was a really hissy and damaged tape and my car's deck wasn't too great anyway, so I misheard "1-800-pee-pee-5-1-doo-doo" as "1-800-pee-pee-19-doo-doo" circa 0:18.  Naturally, I picked the wrong pp19dd and stuck to it.

**Comment by tyanata** [comment]
Hello,
Very nice library! 
But it is not working in python3.6, the problem is in following line: return( ret ) . In order the issue to be fixed the line has to be amended to return( list(ret) )

And also the line: import curses.wrapper is not needed.

**Comment by pp19dd** [comment]
@tyanata hello from the future (also sorry to get back here so late), but thanks for the tip. I've made code updates and fixes to make it compatible with 3.6.

**Comment by pp19dd** [comment]
@vindarel howdy, and sorry, while I'll reconsider doing that in the future I obviously don't have the mental bandwidth to maintain this project that actively now.  So, I've decided to keep the project lightweight, and for that reason not going to enter it into a package manager environment at this time.

**Comment by vindarel** [comment]
Hello, actually that shouldn't be a big deal given we can install github packages with sthg like `pip install -e git+http://github.../project.git#egg=project`.

But still, in pypi would be nice.

(and oh, I wouldn't close the issue so than others can more easily find it and see this status).
